# Practice on vectors in Linear Algebra 

### Types of vector creation

In [3]:
import numpy as np
from numpy.conftest import dtype
from numpy.ma.core import zeros

asList = [1,2,3]
asArray = np.array([1,2,3])
rowVector = np.array([ [1,2,3] ])
columnVector = np.array([ [1],[2],[3] ])
rowVector.T

array([[1],
       [2],
       [3]])

## Check out the outline

In [1]:
print(f"asList:{np.shape(asList)}")
print(f"asArray:{asArray.shape}") 
print(f"rowVector:{rowVector.shape}")
print(f"columnVector:{columnVector.shape}")
rowVector

NameError: name 'np' is not defined

### Vector addition

In [2]:
import numpy as np
vec1 = np.array([[1],[2],[3]])
vec2 = np.array([[10],[20],[30]])
vec_add_1 = np.add(vec1,vec2)
vec_add_2  = vec1 + vec2
print(vec_add_1)

[[11]
 [22]
 [33]]


### Vector subtract

In [31]:
vec1 = np.array([[1],[2],[3]])
vec2 = np.array([[10],[20],[30]])
vec_sub_1 = np.subtract(vec2,vec1)
vec_sub_2 = vec2 - vec1
print(vec_sub_2)

[[ 8]
 [18]
 [28]]


### vector multiplication by scalar

In [33]:
vector = np.array([ [2,10,9] ])
scalar = 5
print(np.multiply(vector,5))
print(vector * scalar)

[[10 50 45]]
[[10 50 45]]


### Vector norm and mathematical dimension

In [14]:
vector = np.array([1, 2, 3, 7, 8, 9])
vector_math_dimension = len(vector) #length
vector_norm = np.linalg.norm(vector)
print(vector_norm)
print(vector_math_dimension)
zero_vector = np.multiply(vector,1/vector_norm)
print(zero_vector)
print(np.linalg.norm(zero_vector))

14.422205101855956
6
[0.06933752 0.13867505 0.20801257 0.48536267 0.5547002  0.62403772]
1.0


### Dot product of vectors

In [10]:
vector_first = np.array([1,2,3,4])
vector_second = np.array([5,6,7,8])
print(np.dot(vector_first,vector_second))
res_number = 0
res_list = list()
for index in range(len(vector_second)):
    res_number += vector_second[index]*vector_first[index]
    res_list.append(vector_second[index]*vector_first[index])
else:
    res_list = sum(res_list)
print(res_list,res_number)


70
70 70
